[ERROR] 2019-07-09 12:58:18,169 | /opt/bench/erpnext/apps/frappe/frappe/app.py:
Site: erpnewsite
Form Dict: {
 "args": "{\"item_code\":\"27A\",\"warehouse\":\"Kerugoya Hospital Store - HM\",\"doctype\":\"Material Request\",\"buying_price_list\":\"Standard Buying\",\"currency\":\"KES\",\"name\":\"New Material Request 2\",\"qty\":\"100\",\"stock_qty\":\"\",\"company\":\"HMIS\",\"conversion_rate\":1,\"material_request_type\":\"Purchase\",\"plc_conversion_rate\":1,\"rate\":0,\"conversion_factor\":\"300mg\"}", 
 "cmd": "erpnext.stock.get_item_details.get_item_details"
}
Request Error
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 20, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 1013, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/erpnext/erpnext/stock/get_item_details.py", line 81, in get_item_details
    out.amount = flt(args.qty * out.rate)
TypeError: can't multiply sequence by non-int of type 'float'
[ERROR] 2019-07-10 12:34:28,556 | /opt/bench/erpnext/apps/frappe/frappe/app.py:
Site: erpnewsite
Form Dict: {
 "cmd": "frappe.utils.help.get_help", 
 "text": "Mode of payment type"
}
Request Error
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 20, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 1013, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/help.py", line 26, in get_help
    return HelpDatabase().search(text)
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/help.py", line 81, in search
    select title, intro, path from help where match(content) against (%s) limit 10''', ('%'+words+'%', words))
  File "/opt/bench/erpnext/apps/frappe/frappe/database/database.py", line 155, in sql
    self._cursor.execute(query, values)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
ProgrammingError: (1146, u"Table 'erpnewsite.help' doesn't exist")
